### ISSUE TITLE
Remote compilation

### ISSUE THREAD

**Issue by anandj91** [CentML/centml-python-client#3]
```[tasklist]
### Tasks
- [ ] https://github.com/CentML/centml-python-client/pull/9
- [ ] https://github.com/CentML/centml-python-client/issues/8
- [ ] https://github.com/CentML/centml-python-client/issues/10
```
